use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :project1, Project1Web.Endpoint,
  server: true,
  root: ".",
  version: Application.spec(:phoenix_distillery, :vsn),
  http: [:inet6, port: {:system, "PORT"}],
  url: [host: "checkers.ericgift.com", port: 80],
  cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info


path = Path.expand("~/.config/project1.secret")
unless File.exists?(path) do
  secret = Base.encode16(:crypto.strong_rand_bytes(32))
  File.write!(path, secret)
end
secret = File.read!(path)

config :project1, Project1Web.Endpoint,
  secret_key_base: secret
